/**
 * Branding.h
 * Provides branding information for c++ projects.
 **/

#ifndef _BRANDING_H_
#define _BRANDING_H_

/**
 * macro adaption for different compilers
 **/
#if MIDLBRANDING
	//we run from MIDL compiler
	#define TEXT(quote) quote
	#define MAKEUUIDSTR(x)	x
	#define ___noncppbuild
#endif

#if RC_INVOKED
	//we run from resource compiler
	#define ___noncppbuild
#endif

#ifndef ___noncppbuild
	//we run from c compiler
	#include <Windows.h> //needed for the TEXT - Macro
#endif

#ifndef MAKEUUIDSTR
	#define MAKEUUIDSTR(x) TEXT("{") TEXT(#x) TEXT("}")
#endif

/**
 * identifier for debug builds
 **/
#if _DEBUG
	#define BRANDINGDEVEXTENSION TEXT("-Dev")
#else 
	#define BRANDINGDEVEXTENSION 
#endif

// company definitions
#define BRANDING_COMPANY_NAME TEXT(/*COMPANY*/"Perceptive Software Deutschland GmbH"/*COMPANY*/)
#define BRANDING_COMPANY_NAME_TECHNICAL TEXT(/*COMPANY_TECHNICAL*/"Perceptive"/*COMPANY_TECHNICAL*/) BRANDINGDEVEXTENSION
#define BRANDING_COMPANY_WEBSITE TEXT(/*COMPANY_WEBSITE*/"http://www.perceptivesoftware.com"/*COMPANY_WEBSITE*/)

// product definitions
#define BRANDING_PRODUCT_NAME TEXT(/*PRODUCT*/"fileNshare"/*PRODUCT*/)
#define BRANDING_PRODUCT_NAME_TECHNICAL_FILESYSTEM TEXT(/*PRODUCT_TECHNICAL_FILESYSTEM*/"fileNshare"/*PRODUCT_TECHNICAL_FILESYSTEM*/) BRANDINGDEVEXTENSION
#define BRANDING_PRODUCT_NAME_TECHNICAL_MENU TEXT(/*PRODUCT_TECHNICAL_MENU*/"fileNshare"/*PRODUCT_TECHNICAL_MENU*/) BRANDINGDEVEXTENSION
#define BRANDING_PRODUCT_NAME_TECHNICAL_REGISTRY TEXT(/*PRODUCT_TECHNICAL_REGISTRY*/"fileNshare"/*PRODUCT_TECHNICAL_REGISTRY*/) BRANDINGDEVEXTENSION
#define BRANDING_PRODUCT_VERSION TEXT(/*PRODUCT_VERSION*/"3.0.0"/*PRODUCT_VERSION*/)

// copyright definition
#define BRANDING_COPYRIGHT TEXT(/*COPYRIGHT*/"Copyright © Perceptive Software Deutschland GmbH 2014"/*COPYRIGHT*/)

#define BRANDING_DEFAULT_REMOTE_HOST TEXT(/*DEFAULT_REMOTE_HOST*/"https://fnsdev.psft.co"/*DEFAULT_REMOTE_HOST*/)
#define BRANDING_DEFAULT_REMOTE_SERVICE TEXT(/*DEFAULT_REMOTE_SERVICE*/"/fns-service"/*DEFAULT_REMOTE_SERVICE*/)
#define BRANDING_DEFAULT_REMOTE_CLIENT TEXT(/*DEFAULT_REMOTE_CLIENT*/"/"/*DEFAULT_REMOTE_CLIENT*/)

#define BRANDING_PROTOCOL_SCHEME TEXT(/*PROTOCOL_SCHEME*/"fileNshare"/*PROTOCOL_SCHEME*/) BRANDINGDEVEXTENSION
#define BRANDING_PIPE_NAME TEXT(/*PIPE_NAME*/"4BCCAE44-0B12-4030-8757-7197D2DD7C41"/*PIPE_NAME*/)
#define BRANDING_INSTANCE_MUTEX TEXT(/*INSTANCE_MUTEX*/"775F48AB-36FD-4B1D-8859-EB77004342C6"/*INSTANCE_MUTEX*/)

// identifier for the SDB.Lib.ShellExtension type lib and overlay icons
#define RUNTIME_SHELL_TYPELIB MAKEUUIDSTR(/*UUID_SHELL_TYPELIB*/8AB95277-109F-4AFA-B700-67AEB10AE45D/*UUID_SHELL_TYPELIB*/)

// identifier for the shell menu extension
#define RUNTIME_SHELL_MENU MAKEUUIDSTR(/*UUID_SHELL_MENU*/E3530D60-B312-48E0-8D83-AABE3CCC7553/*UUID_SHELL_MENU*/)

//identifiers for the overlays
#define RUNTIME_SHELL_OVERLAY_OK MAKEUUIDSTR(/*UUID_SHELL_OVERLAY_OK*/BE25AFD4-8A02-4B9F-8E0F-0E02B12E1933/*UUID_SHELL_OVERLAY_OK*/)
#define RUNTIME_SHELL_OVERLAY_CHANGED MAKEUUIDSTR(/*UUID_SHELL_OVERLAY_CHANGED*/55829C1C-B6FA-4561-8B78-8E4C35D15556/*UUID_SHELL_OVERLAY_CHANGED*/)
#define RUNTIME_SHELL_OVERLAY_CONFLICTED MAKEUUIDSTR(/*UUID_SHELL_OVERLAY_CONFLICTED*/C0600077-50CD-4F91-B3A4-43A9EAC964C6/*UUID_SHELL_OVERLAY_CONFLICTED*/)
#define RUNTIME_SHELL_OVERLAY_SYNCING MAKEUUIDSTR(/*UUID_SHELL_OVERLAY_SYNCING*/39AB972A-B0C4-4542-820A-E8E40B329AB5/*UUID_SHELL_OVERLAY_SYNCING*/)
#define RUNTIME_SHELL_OVERLAY_ENCRYPTED MAKEUUIDSTR(/*UUID_SHELL_OVERLAY_ENCRYPTED*/582D8822-0E07-401E-AA3B-8FC499623374/*UUID_SHELL_OVERLAY_ENCRYPTED*/)

//identifier for the infotip handler
#define RUNTIME_SHELL_INFOTIP MAKEUUIDSTR(/*UUID_SHELL_INFOTIP*/5E2BFF2C-BDD9-4E3A-AEA9-3D17580E2EED/*UUID_SHELL_INFOTIP*/)

#endif /* _BRANDING_H_ */